sudo: false
language: python
env:
    - COVERAGE=--with-coverage
python:
    - "2.7"
    - "3.5"
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda create --name test_env --yes python=$TRAVIS_PYTHON_VERSION
    - source activate test_env
    - conda install --yes scipy nose scikit-learn joblib six
install:
    - python setup.py build_ext --inplace
    - if [ "${COVERAGE}" == "--with-coverage" ]; then pip install coverage; fi
    - if [ "${COVERAGE}" == "--with-coverage" ]; then pip install coveralls; fi
    - pip install codecov
script:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then make test-coverage; fi
    - if [ "${COVERAGE}" != "--with-coverage" ]; then make test; fi
after_success:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi
    - codecov
