environment:
  matrix:
    # - PYTHON: "C:\\Python27_32"
    #   PYTHON_VERSION: "2.7"
    #   PYTHON_ARCH: "32"
    #   CONDA_PY: "27"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    #- PYTHON: "C:\\Python34_32"
    #  PYTHON_VERSION: "3.4"
    #  PYTHON_ARCH: "32"
    #  CONDA_PY: "34"

    # - PYTHON: "C:\\Python34_64"
    #   PYTHON_VERSION: "3.4"
    #   PYTHON_ARCH: "64"
    #   CONDA_PY: "34"

    #- PYTHON: "C:\\Python35_32"
    #  PYTHON_VERSION: "3.5"
    #  PYTHON_ARCH: "32"
    #  CONDA_PY: "35"

    # - PYTHON: "C:\\Python35_64"
    #   PYTHON_VERSION: "3.5"
    #   PYTHON_ARCH: "64"
    #   CONDA_PY: "35"

install:
    # https://www.appveyor.com/docs/installed-software#python
    - if "%PYTHON_VERSION%" == "3.4" set "BASE_PYTHON_VERSION=3"
    - if "%PYTHON_VERSION%" == "3.5" set "BASE_PYTHON_VERSION=35"
    - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
    # These are already installed on appveyor.  Update them.
    - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
    - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
    - conda config --set always_yes yes
    - conda update -q conda
    - conda info
    - conda update -q --all
    - python -c "import sys; print(sys.version)"
    - python -c "import sys; print(sys.executable)"
    - python -c "import sys; print(sys.prefix)"
    - conda create --yes --name test_env python=%PYTHON_VERSION%
    - activate test_env
    - conda install -q  six numpy scikit-learn joblib nose
    - conda install -q -c mwojcikowski mingwpy dlfcn
    - pip install coverage coveralls
    - set "CC=gcc"
    - set "CXX=gcc -pthread"
    - python setup.py build_ext --inplace --compiler=mingw32 -llibdl

    - set "CI_NAME=appveyor"
    - set "CI_BRANCH=%APPVEYOR_REPO_BRANCH%"


build: false

test_script:
    - nosetests -s -v --with-coverage compiledtrees
    - coveralls
